rss:
- name: TechCrunch
  url: https://techcrunch.com/feed/
  category: technology
  enabled: true
- name: Engadget
  url: https://www.engadget.com/rss.xml
  category: technology
  enabled: true
- name: Ars Technica
  url: https://feeds.arstechnica.com/arstechnica/index
  category: technology
  enabled: true
- name: Gizmodo
  url: https://gizmodo.com/feed
  category: technology
  enabled: true
- name: ESPN
  url: https://www.espn.com/espn/rss/news
  category: sports
  enabled: true
- name: Bleacher Report
  url: https://bleacherreport.com/articles/feed
  category: sports
  enabled: true
- name: Sky Sports
  url: https://www.skysports.com/rss/12040
  category: sports
  enabled: true
- name: Yahoo Sports
  url: https://sports.yahoo.com/rss/
  category: sports
  enabled: true
- name: CBS Sports
  url: https://www.cbssports.com/rss/news/
  category: sports
  enabled: true
- name: NBC Sports
  url: https://www.nbcsports.com/feed
  category: sports
  enabled: true
- name: Lonely Planet
  url: https://www.lonelyplanet.com/blog/feed
  category: travel
  enabled: true
- name: Travel + Leisure
  url: https://www.travelandleisure.com/feeds/all
  category: travel
  enabled: true
- name: "Cond\xE9 Nast Traveler"
  url: https://www.cntraveler.com/feed/rss
  category: travel
  enabled: true
- name: Fodor's Travel
  url: https://www.fodors.com/news/feed
  category: travel
  enabled: true
- name: Vogue
  url: https://www.vogue.com/feed/rss
  category: style
  enabled: true
- name: GQ
  url: https://www.gq.com/feed/rss
  category: style
  enabled: true
- name: Hypebeast
  url: https://hypebeast.com/feed
  category: style
  enabled: true
- name: Esquire
  url: https://www.esquire.com/rss/all.xml
  category: style
  enabled: true
- name: Fashionista
  url: https://fashionista.com/.rss/full/
  category: style
  enabled: true
- name: Well+Good
  url: https://www.wellandgood.com/feed/
  category: wellbeing
  enabled: true
- name: Healthline
  url: https://www.healthline.com/rss/nutrition
  category: wellbeing
  enabled: true
- name: Psychology Today
  url: https://www.psychologytoday.com/us/front/feed
  category: wellbeing
  enabled: true
- name: MindBodyGreen
  url: https://www.mindbodygreen.com/rss/feed.xml
  category: wellbeing
  enabled: true
- name: Self Magazine
  url: https://www.self.com/feed/rss
  category: wellbeing
  enabled: true
- name: The Verge
  url: http://www.theverge.com/rss/full.xml
  category: technology
  enabled: true
- name: Business Insider
  url: http://feeds2.feedburner.com/businessinsider
  category: wellbeing
  enabled: true
- name: 'Politico '
  url: http://feeds.politico.com/politico/rss/politicopicks
  category: wellbeing
  enabled: true
- name: Wired
  url: http://feeds.wired.com/wired/index
  category: technology
  enabled: true
- name: xkcd
  url: http://xkcd.com/rss.xml
  category: wellbeing
  enabled: true
- name: Entrepreneur
  url: http://feeds.feedburner.com/entrepreneur/latest
  category: wellbeing
  enabled: true
- name: Leading Blog
  url: http://www.leadershipnow.com/leadingblog/atom.xml
  category: wellbeing
  enabled: true
- name: Greg Mankiw's Blog
  url: http://gregmankiw.blogspot.com/feeds/posts/default
  category: wellbeing
  enabled: true
- name: Management Blog
  url: http://www.managementblog.org/feed/
  category: wellbeing
  enabled: true
- name: DAILY WRITING TIPS
  url: http://feeds.feedburner.com/DailyWritingTips
  category: wellbeing
  enabled: true
- name: Ann Handley
  url: http://feeds.feedburner.com/ANNARCHY
  category: wellbeing
  enabled: true
- name: smitten kitchen
  url: http://feeds.feedburner.com/smittenkitchen
  category: wellbeing
  enabled: true
- name: The Points Guy Articles
  url: http://feeds.feedburner.com/thepointsguy
  category: travel
  enabled: true
- name: Stereogum
  url: http://feeds.feedburner.com/stereogum/cBYa
  category: wellbeing
  enabled: true
- name: Boing Boing
  url: http://feeds.boingboing.net/boingboing/iBag
  category: wellbeing
  enabled: true
- name: 'New York Times - Modern Love '
  url: http://topics.nytimes.com/top/features/style/fashionandstyle/columns/modernlove/?rss=1
  category: wellbeing
  enabled: true
- name: Calculated Risk
  url: http://www.calculatedriskblog.com/feeds/posts/default
  category: wellbeing
  enabled: true
- name: Electrek
  url: http://electrek.co/feed/
  category: technology
  enabled: true
- name: 'Harvard Business Review '
  url: http://feeds.harvardbusiness.org/harvardbusiness/
  category: wellbeing
  enabled: true
- name: BloombergNEF
  url: http://www.bnef.com/bnef/feed/
  category: technology
  enabled: true
- name: Above the Law
  url: http://www.abovethelaw.com/index.xml
  category: wellbeing
  enabled: true
- name: 4Hoteliers
  url: http://www.4hoteliers.com/rss/4htopnews.xml
  category: travel
  enabled: true
- name: RCR Wireless News
  url: http://www.rcrwireless.com/article/feed/
  category: technology
  enabled: true
- name: AgFunderNews
  url: http://agfundernews.com/feed
  category: wellbeing
  enabled: true
- name: Lowering the Bar
  url: http://www.loweringthebar.net/atom.xml
  category: wellbeing
  enabled: true
- name: Runway Girl
  url: http://www.runwaygirlnetwork.com/feed/
  category: travel
  enabled: true
- name: NYT > Top Stories
  url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml
  category: wellbeing
  enabled: true
- name: Skift
  url: http://skift.com/feed/
  category: travel
  enabled: true
- name: Grist
  url: http://feeds.grist.org/rss/gristfeed
  category: wellbeing
  enabled: true
- name: Inman
  url: http://feeds.feedburner.com/inmannews
  category: wellbeing
  enabled: true
- name: 'The Atlantic '
  url: http://feeds.feedburner.com/TheAtlantic
  category: wellbeing
  enabled: true
web: []
